[package]
name = "iso8601"
version = "0.2.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>", "Hendrik Sollich <hendrik@hoodie.de>"]

description = "Parsing ISO8601 dates using nom"

homepage = "http://badboy.github.io/iso8601/"
repository = "https://github.com/badboy/iso8601"
documentation = "http://badboy.github.io/iso8601/"
license = "MIT"
readme = "README.md"


[dependencies]
nom = "4.0.0-beta1"
clippy = {version = ">0.0.0", optional = true}

[features]
default = []
